Algoritmo "soma de 4 numeros"

Var
x, y, z, numero, resultado : inteiro


Inicio

escreval("DIgite o primeiro numero:")
  leia(x)
     limpaTela()
  escreval("Digite o segundo numero:")
  leia(y)
  limpaTela()
  escreval("Digite o terceiro numero:")
  leia(z)
  limpaTela()
  escreval("Digite o ultimo numero:")
  leia(numero)
  limpaTela()
  resultado <- x + y + z + numero
  escreval("O resultado da soma é : ", resultado)




Fimalgoritmo