Algoritmo "recepcao"

Var
nome, email : caractere
idade : inteiro

Inicio
escreval("boa tarde! DIgite o seu nome: ")
leia (nome)
limpaTela()

escreval ("Digite a sua idade: ")
leia(idade)
limpaTela()

Escreval ("digite o seu email: ")
leia(email)
limpaTela()

escreval("Cadastro efetuado com sucesso!")
escreval("******************")
escreval("Usuario : ",nome)
escreval("idade :",idade)
escreval("email :",email)
escreval("******************")

Fimalgoritmo